import 'dart:ui';

import 'package:b16pdf/b16_hep_djijdow/b16_storage_hep_fjiejfe/b16_storage_hep_fefjei/b16_language_selected_fjiefjoe.dart';
import 'package:get/get.dart';

final class B16LanguageOptionQxnvra {
  const B16LanguageOptionQxnvra({
    required this.b16LocaleKpwmze,
    required this.b16NativeNameVqtxla,
  });

  final Locale b16LocaleKpwmze;
  final String b16NativeNameVqtxla;
}

final class B16LanguageHepKqmvza extends Translations {
  B16LanguageHepKqmvza();

  static const Locale b16FallbackLocaleCqnxwa = Locale('en');

  static const List<B16LanguageOptionQxnvra> b16LanguageOptionsVqmpze = [
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('en'),
      b16NativeNameVqtxla: 'English',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('fr'),
      b16NativeNameVqtxla: 'Français',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('ja'),
      b16NativeNameVqtxla: '日本語',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('ko'),
      b16NativeNameVqtxla: '한국어',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('de'),
      b16NativeNameVqtxla: 'Deutsch',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('es'),
      b16NativeNameVqtxla: 'Español',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('it'),
      b16NativeNameVqtxla: 'Italiano',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('pt'),
      b16NativeNameVqtxla: 'Português',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('ru'),
      b16NativeNameVqtxla: 'Русский',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('zh', 'TW'),
      b16NativeNameVqtxla: '繁體中文',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('zh', 'CN'),
      b16NativeNameVqtxla: '简体中文',
    ),
    B16LanguageOptionQxnvra(
      b16LocaleKpwmze: Locale('ar'),
      b16NativeNameVqtxla: 'العربية',
    ),
  ];

  static List<Locale> get b16SupportedLocalesJxqvte => b16LanguageOptionsVqmpze
      .map((B16LanguageOptionQxnvra b16OptionTzpwka) {
        return b16OptionTzpwka.b16LocaleKpwmze;
      })
      .toList(growable: false);

  static Locale b16ResolveInitialLocaleRmqxve() {
    final String b16StoredLanguagePqtwza =
        B16LanguageSelectedFjiefjoe.b16ReadLanguageVqmxpe();
    if (b16StoredLanguagePqtwza.isNotEmpty) {
      return b16NormalizeLocaleHqvzsa(b16StoredLanguagePqtwza);
    }
    return b16NormalizeLocaleHqvzsa(
      PlatformDispatcher.instance.locale.toLanguageTag(),
    );
  }

  static Future<void> b16SelectLanguageGqmwxe(Locale b16LocaleVxqpta) async {
    final Locale b16NormalizedLocaleKzmrwe = b16NormalizeLocaleHqvzsa(
      b16LocaleVxqpta.toLanguageTag(),
    );
    await B16LanguageSelectedFjiefjoe.b16SaveLanguageDqnvya(
      b16NormalizedLocaleKzmrwe.toLanguageTag(),
    );
    await Get.updateLocale(b16NormalizedLocaleKzmrwe);
  }

  static Locale b16NormalizeLocaleHqvzsa(String b16LanguageTagCqmwpe) {
    final String b16NormalizedTagJxrvta = b16LanguageTagCqmwpe
        .trim()
        .replaceAll('_', '-')
        .toLowerCase();
    final List<String> b16TagPartsNqvzke = b16NormalizedTagJxrvta.split('-');
    final String b16LanguageCodeTpmxwa = b16TagPartsNqvzke.first;

    if (b16LanguageCodeTpmxwa == 'zh') {
      final bool b16UseTraditionalHqnvze = b16TagPartsNqvzke.any(
        (String b16PartVqmxra) =>
            const {'tw', 'hk', 'mo', 'hant'}.contains(b16PartVqmxra),
      );
      return Locale('zh', b16UseTraditionalHqnvze ? 'TW' : 'CN');
    }

    const Set<String> b16SupportedCodesRkqvma = {
      'en',
      'fr',
      'ja',
      'ko',
      'de',
      'es',
      'it',
      'pt',
      'ru',
      'ar',
    };
    return b16SupportedCodesRkqvma.contains(b16LanguageCodeTpmxwa)
        ? Locale(b16LanguageCodeTpmxwa)
        : b16FallbackLocaleCqnxwa;
  }

  @override
  Map<String, Map<String, String>> get keys => const {
    'en': {
      'PDF tools': 'PDF tools',
      'Scan To': 'Scan To',
      'Image To': 'Image To',
      'System': 'System',
      'Add Widget': 'Add Widget',
      'Add widget with one click to open files':
          'Add widget with one click to open files',
      'Home': 'Home',
      'Merge': 'Merge',
      'Import': 'Import',
      'Convert': 'Convert',
      'Add': 'Add',
      'Why are you uninstalling?': 'Why are you uninstalling?',
      'Hard to use': 'Hard to use',
      'Frequent ad interference': 'Frequent ad interference',
      'Poor PDF reading experience': 'Poor PDF reading experience',
      'Too many notifications': 'Too many notifications',
      "Editing features don't meet needs": "Editing features don't meet needs",
      'Phone has built-in PDF tools': 'Phone has built-in PDF tools',
      'Other (Please specify)': 'Other (Please specify)',
      'Please enter the reason for uninstalling All PDF':
          'Please enter the reason for uninstalling All PDF',
      "Don't uninstall for now": "Don't uninstall for now",
      'Uninstall': 'Uninstall',
      'New version coming soon!': 'New version coming soon!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!',
      'Continue using for free': 'Continue using for free',
      'Leave anyway': 'Leave anyway',
      'Preference': 'Preference',
      'App Language': 'App Language',
      'Tools & Settings': 'Tools & Settings',
      'This app has an update': 'This app has an update',
      'Please upgrade to enjoy the latest functions.':
          'Please upgrade to enjoy the latest functions.',
      'All notifications': 'All notifications',
      'Update now': 'Update now',
      'Welcome': 'Welcome',
      'Choose your preferred language to get started.':
          'Choose your preferred language to get started.',
      'OK': 'OK',
      'Color': 'Color',
      'Width': 'Width',
      'Edit': 'Edit',
      'Save': 'Save',
      'Saving...': 'Saving...',
      'Saved successfully': 'Saved successfully',
      'Preview unavailable': 'Preview unavailable',
      'File not found': 'File not found',
      'Permission Required': 'Permission Required',
      'Allow': 'Allow',
      'Please allow storage access to continue.':
          'Please allow storage access to continue.',
      'Please allow camera access to continue.':
          'Please allow camera access to continue.',
      'Please allow access to continue.': 'Please allow access to continue.',
      'Sort By': 'Sort By',
      'Date(Newest First)': 'Date (Newest First)',
      'Date(Oldest First)': 'Date (Oldest First)',
      'Name(A-Z)': 'Name (A-Z)',
      'Name(Z-A)': 'Name (Z-A)',
      'Cancel': 'Cancel',
      '{n} Selected': '{n} Selected',
      'Select All': 'Select All',
      'Delete': 'Delete',
      'Files': 'Files',
      'Tools': 'Tools',
      'Search...': 'Search...',
      'All': 'All',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'To access features instantly, add the widget!',
      'Grant': 'Grant',
      'Local Storage': 'Local Storage',
      'Sort': 'Sort',
      'Select': 'Select',
      'No permissions granted': 'No permissions granted',
      'Permission is required to access all files':
          'Permission is required to access all files',
      'Go to settings': 'Go to settings',
      'PDF': 'PDF',
      'Your pocket file pro': 'Your pocket file pro',
      'Unlock Full PDF Potential': 'Unlock Full PDF Potential',
      'Step 1: find PDF flow in the list below.':
          'Step 1: find PDF flow in the list below.',
      'Step 2: toggle the switch to ON.': 'Step 2: toggle the switch to ON.',
      'Continue': 'Continue',
      'Later': 'Later',
      'Almost there! Unlock your full potential':
          'Almost there! Unlock your full potential',
      'Find {n} below and toggle the switch to ON.':
          'Find {n} below and toggle the switch to ON.',
    },
    'fr': {
      'PDF tools': 'Outils PDF',
      'Scan To': 'Numériser en',
      'Image To': 'Image en',
      'System': 'Système',
      'Add Widget': 'Ajouter un widget',
      'Add widget with one click to open files':
          'Ajoutez le widget en un clic pour ouvrir vos fichiers',
      'Home': 'Accueil',
      'Merge': 'Fusionner',
      'Import': 'Importer',
      'Convert': 'Convertir',
      'Add': 'Ajouter',
      'Why are you uninstalling?': 'Pourquoi désinstallez-vous l’application ?',
      'Hard to use': 'Difficile à utiliser',
      'Frequent ad interference': 'Publicités trop fréquentes',
      'Poor PDF reading experience': 'Mauvaise expérience de lecture PDF',
      'Too many notifications': 'Trop de notifications',
      "Editing features don't meet needs":
          'Les fonctions d’édition ne répondent pas à mes besoins',
      'Phone has built-in PDF tools': 'Mon téléphone dispose déjà d’outils PDF',
      'Other (Please specify)': 'Autre (veuillez préciser)',
      'Please enter the reason for uninstalling All PDF':
          'Veuillez indiquer pourquoi vous désinstallez All PDF',
      "Don't uninstall for now": 'Ne pas désinstaller maintenant',
      'Uninstall': 'Désinstaller',
      'New version coming soon!': 'Une nouvelle version arrive bientôt !',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Nous avons bien reçu votre avis ! Il nous est précieux. Nous améliorons continuellement l’expérience et une nouvelle version sera bientôt disponible. Restez avec nous !',
      'Continue using for free': 'Continuer gratuitement',
      'Leave anyway': 'Quitter quand même',
      'Preference': 'Préférences',
      'App Language': 'Langue de l’application',
      'Tools & Settings': 'Outils et paramètres',
      'This app has an update': 'Cette application a une mise à jour',
      'Please upgrade to enjoy the latest functions.':
          'Effectuez la mise à jour pour profiter des dernières fonctionnalités.',
      'All notifications': 'Toutes les notifications',
      'Update now': 'Mettre à jour',
      'Welcome': 'Bienvenue',
      'Choose your preferred language to get started.':
          'Choisissez votre langue préférée pour commencer.',
      'OK': 'OK',
      'Color': 'Couleur',
      'Width': 'Épaisseur',
      'Edit': 'Modifier',
      'Save': 'Enregistrer',
      'Saving...': 'Enregistrement...',
      'Saved successfully': 'Enregistré avec succès',
      'Preview unavailable': 'Aperçu indisponible',
      'File not found': 'Fichier introuvable',
      'Permission Required': 'Autorisation requise',
      'Allow': 'Autoriser',
      'Please allow storage access to continue.':
          'Autorisez l’accès au stockage pour continuer.',
      'Please allow camera access to continue.':
          'Autorisez l’accès à l’appareil photo pour continuer.',
      'Please allow access to continue.': 'Autorisez l’accès pour continuer.',
      'Sort By': 'Trier par',
      'Date(Newest First)': 'Date (plus récent en premier)',
      'Date(Oldest First)': 'Date (plus ancien en premier)',
      'Name(A-Z)': 'Nom (A-Z)',
      'Name(Z-A)': 'Nom (Z-A)',
      'Cancel': 'Annuler',
      '{n} Selected': '{n} sélectionné(s)',
      'Select All': 'Tout sélectionner',
      'Delete': 'Supprimer',
      'Files': 'Fichiers',
      'Tools': 'Outils',
      'Search...': 'Rechercher...',
      'All': 'Tous',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'Ajoutez le widget pour accéder instantanément aux fonctionnalités !',
      'Grant': 'Autoriser',
      'Local Storage': 'Stockage local',
      'Sort': 'Trier',
      'Select': 'Sélectionner',
      'No permissions granted': 'Aucune autorisation accordée',
      'Permission is required to access all files':
          'Une autorisation est nécessaire pour accéder à tous les fichiers',
      'Go to settings': 'Accéder aux paramètres',
      'PDF': 'PDF',
      'Your pocket file pro': 'Vos fichiers toujours à portée de main',
      'Unlock Full PDF Potential': 'Libérez tout le potentiel de PDF',
      'Step 1: find PDF flow in the list below.':
          'Étape 1 : trouvez PDF flow dans la liste ci-dessous.',
      'Step 2: toggle the switch to ON.': 'Étape 2 : activez l’interrupteur.',
      'Continue': 'Continuer',
      'Later': 'Plus tard',
      'Almost there! Unlock your full potential':
          'Vous y êtes presque ! Libérez tout votre potentiel',
      'Find {n} below and toggle the switch to ON.':
          'Trouvez {n} ci-dessous et activez l’interrupteur.',
    },
    'ja': {
      'PDF tools': 'PDFツール',
      'Scan To': 'スキャンして',
      'Image To': '画像から',
      'System': 'システム',
      'Add Widget': 'ウィジェットを追加',
      'Add widget with one click to open files': 'ワンタップでファイルを開くウィジェットを追加',
      'Home': 'ホーム',
      'Merge': '結合',
      'Import': '読み込み',
      'Convert': '変換',
      'Add': '追加',
      'Why are you uninstalling?': 'アンインストールする理由を教えてください',
      'Hard to use': '使いにくい',
      'Frequent ad interference': '広告が頻繁に表示される',
      'Poor PDF reading experience': 'PDFを快適に読めない',
      'Too many notifications': '通知が多すぎる',
      "Editing features don't meet needs": '編集機能がニーズに合わない',
      'Phone has built-in PDF tools': '端末にPDFツールが標準搭載されている',
      'Other (Please specify)': 'その他（具体的に入力してください）',
      'Please enter the reason for uninstalling All PDF':
          'All PDFをアンインストールする理由を入力してください',
      "Don't uninstall for now": '今はアンインストールしない',
      'Uninstall': 'アンインストール',
      'New version coming soon!': '新しいバージョンを近日公開！',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'ご意見を受け付けました。いただいた情報は私たちにとって大切です。より良い製品体験を目指して改善を続けており、新しいバージョンも近日公開予定です。ぜひ引き続きご利用ください。',
      'Continue using for free': '無料で使い続ける',
      'Leave anyway': 'それでも終了する',
      'Preference': '設定',
      'App Language': 'アプリの言語',
      'Tools & Settings': 'ツールと設定',
      'This app has an update': 'アプリの更新があります',
      'Please upgrade to enjoy the latest functions.': '最新機能を利用するには更新してください。',
      'All notifications': 'すべての通知',
      'Update now': '今すぐ更新',
      'Welcome': 'ようこそ',
      'Choose your preferred language to get started.': '使用する言語を選択してください。',
      'OK': 'OK',
      'Color': '色',
      'Width': '太さ',
      'Edit': '編集',
      'Save': '保存',
      'Saving...': '保存中...',
      'Saved successfully': '保存しました',
      'Preview unavailable': 'プレビューできません',
      'File not found': 'ファイルが見つかりません',
      'Permission Required': '権限が必要です',
      'Allow': '許可',
      'Please allow storage access to continue.': '続行するにはストレージへのアクセスを許可してください。',
      'Please allow camera access to continue.': '続行するにはカメラへのアクセスを許可してください。',
      'Please allow access to continue.': '続行するにはアクセスを許可してください。',
      'Sort By': '並べ替え',
      'Date(Newest First)': '日付（新しい順）',
      'Date(Oldest First)': '日付（古い順）',
      'Name(A-Z)': '名前（A-Z）',
      'Name(Z-A)': '名前（Z-A）',
      'Cancel': 'キャンセル',
      '{n} Selected': '{n}件選択済み',
      'Select All': 'すべて選択',
      'Delete': '削除',
      'Files': 'ファイル',
      'Tools': 'ツール',
      'Search...': '検索...',
      'All': 'すべて',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'ウィジェットを追加すると、機能にすぐアクセスできます！',
      'Grant': '許可',
      'Local Storage': 'ローカルストレージ',
      'Sort': '並べ替え',
      'Select': '選択',
      'No permissions granted': '権限が許可されていません',
      'Permission is required to access all files': 'すべてのファイルにアクセスするには権限が必要です',
      'Go to settings': '設定を開く',
      'PDF': 'PDF',
      'Your pocket file pro': 'ポケットの中のファイル管理',
      'Unlock Full PDF Potential': 'PDFの可能性を最大限に引き出す',
      'Step 1: find PDF flow in the list below.':
          'ステップ1：下のリストからPDF flowを見つけます。',
      'Step 2: toggle the switch to ON.': 'ステップ2：スイッチをオンにします。',
      'Continue': '続ける',
      'Later': '後で',
      'Almost there! Unlock your full potential': 'あと少しです！すべての機能を有効にしましょう',
      'Find {n} below and toggle the switch to ON.':
          '下から{n}を見つけて、スイッチをオンにしてください。',
    },
    'ko': {
      'PDF tools': 'PDF 도구',
      'Scan To': '스캔하여',
      'Image To': '이미지를',
      'System': '시스템',
      'Add Widget': '위젯 추가',
      'Add widget with one click to open files': '한 번의 터치로 파일을 여는 위젯을 추가하세요',
      'Home': '홈',
      'Merge': '병합',
      'Import': '가져오기',
      'Convert': '변환',
      'Add': '추가',
      'Why are you uninstalling?': '앱을 삭제하는 이유가 무엇인가요?',
      'Hard to use': '사용하기 어려움',
      'Frequent ad interference': '광고가 너무 자주 표시됨',
      'Poor PDF reading experience': 'PDF 읽기 환경이 좋지 않음',
      'Too many notifications': '알림이 너무 많음',
      "Editing features don't meet needs": '편집 기능이 필요에 맞지 않음',
      'Phone has built-in PDF tools': '휴대전화에 PDF 도구가 내장되어 있음',
      'Other (Please specify)': '기타(직접 입력)',
      'Please enter the reason for uninstalling All PDF':
          'All PDF를 삭제하는 이유를 입력하세요',
      "Don't uninstall for now": '지금은 삭제하지 않기',
      'Uninstall': '삭제',
      'New version coming soon!': '새 버전이 곧 출시됩니다!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          '소중한 의견이 접수되었습니다. 보내주신 정보는 제품 개선에 큰 도움이 됩니다. 더 나은 사용 경험을 위해 계속 개선 중이며 새 버전도 곧 출시됩니다. 계속 함께해 주세요!',
      'Continue using for free': '무료로 계속 사용',
      'Leave anyway': '그래도 나가기',
      'Preference': '환경설정',
      'App Language': '앱 언어',
      'Tools & Settings': '도구 및 설정',
      'This app has an update': '앱 업데이트가 있습니다',
      'Please upgrade to enjoy the latest functions.': '최신 기능을 이용하려면 업데이트하세요.',
      'All notifications': '모든 알림',
      'Update now': '지금 업데이트',
      'Welcome': '환영합니다',
      'Choose your preferred language to get started.': '시작하려면 선호하는 언어를 선택하세요.',
      'OK': '확인',
      'Color': '색상',
      'Width': '두께',
      'Edit': '편집',
      'Save': '저장',
      'Saving...': '저장 중...',
      'Saved successfully': '저장되었습니다',
      'Preview unavailable': '미리보기를 사용할 수 없습니다',
      'File not found': '파일을 찾을 수 없습니다',
      'Permission Required': '권한 필요',
      'Allow': '허용',
      'Please allow storage access to continue.': '계속하려면 저장소 접근을 허용하세요.',
      'Please allow camera access to continue.': '계속하려면 카메라 접근을 허용하세요.',
      'Please allow access to continue.': '계속하려면 접근을 허용하세요.',
      'Sort By': '정렬 기준',
      'Date(Newest First)': '날짜(최신순)',
      'Date(Oldest First)': '날짜(오래된순)',
      'Name(A-Z)': '이름(A-Z)',
      'Name(Z-A)': '이름(Z-A)',
      'Cancel': '취소',
      '{n} Selected': '{n}개 선택됨',
      'Select All': '전체 선택',
      'Delete': '삭제',
      'Files': '파일',
      'Tools': '도구',
      'Search...': '검색...',
      'All': '전체',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          '위젯을 추가하면 기능에 바로 접근할 수 있습니다!',
      'Grant': '권한 허용',
      'Local Storage': '로컬 저장소',
      'Sort': '정렬',
      'Select': '선택',
      'No permissions granted': '권한이 허용되지 않았습니다',
      'Permission is required to access all files': '모든 파일에 접근하려면 권한이 필요합니다',
      'Go to settings': '설정으로 이동',
      'PDF': 'PDF',
      'Your pocket file pro': '주머니 속 파일 전문가',
      'Unlock Full PDF Potential': 'PDF의 모든 기능을 활용하세요',
      'Step 1: find PDF flow in the list below.':
          '1단계: 아래 목록에서 PDF flow를 찾으세요.',
      'Step 2: toggle the switch to ON.': '2단계: 스위치를 켜세요.',
      'Continue': '계속',
      'Later': '나중에',
      'Almost there! Unlock your full potential': '거의 다 됐어요! 모든 기능을 활성화하세요',
      'Find {n} below and toggle the switch to ON.': '아래에서 {n}을 찾아 스위치를 켜세요.',
    },
    'de': {
      'PDF tools': 'PDF-Werkzeuge',
      'Scan To': 'Scannen zu',
      'Image To': 'Bild zu',
      'System': 'System',
      'Add Widget': 'Widget hinzufügen',
      'Add widget with one click to open files':
          'Widget hinzufügen, um Dateien mit einem Klick zu öffnen',
      'Home': 'Start',
      'Merge': 'Zusammenführen',
      'Import': 'Importieren',
      'Convert': 'Konvertieren',
      'Add': 'Hinzufügen',
      'Why are you uninstalling?': 'Warum deinstallieren Sie die App?',
      'Hard to use': 'Schwierig zu bedienen',
      'Frequent ad interference': 'Zu häufige Werbung',
      'Poor PDF reading experience': 'Schlechtes PDF-Leseerlebnis',
      'Too many notifications': 'Zu viele Benachrichtigungen',
      "Editing features don't meet needs":
          'Bearbeitungsfunktionen entsprechen nicht meinen Anforderungen',
      'Phone has built-in PDF tools':
          'Das Telefon hat bereits integrierte PDF-Werkzeuge',
      'Other (Please specify)': 'Sonstiges (bitte angeben)',
      'Please enter the reason for uninstalling All PDF':
          'Bitte geben Sie den Grund für die Deinstallation von All PDF ein',
      "Don't uninstall for now": 'Vorerst nicht deinstallieren',
      'Uninstall': 'Deinstallieren',
      'New version coming soon!': 'Eine neue Version kommt bald!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Ihr Feedback ist bei uns eingegangen und sehr wichtig. Wir verbessern das Produkterlebnis kontinuierlich und veröffentlichen bald eine neue Version. Bleiben Sie bei uns!',
      'Continue using for free': 'Kostenlos weiterverwenden',
      'Leave anyway': 'Trotzdem verlassen',
      'Preference': 'Einstellungen',
      'App Language': 'App-Sprache',
      'Tools & Settings': 'Werkzeuge und Einstellungen',
      'This app has an update': 'Für diese App ist ein Update verfügbar',
      'Please upgrade to enjoy the latest functions.':
          'Aktualisieren Sie die App, um die neuesten Funktionen zu nutzen.',
      'All notifications': 'Alle Benachrichtigungen',
      'Update now': 'Jetzt aktualisieren',
      'Welcome': 'Willkommen',
      'Choose your preferred language to get started.':
          'Wählen Sie Ihre bevorzugte Sprache aus.',
      'OK': 'OK',
      'Color': 'Farbe',
      'Width': 'Breite',
      'Edit': 'Bearbeiten',
      'Save': 'Speichern',
      'Saving...': 'Wird gespeichert...',
      'Saved successfully': 'Erfolgreich gespeichert',
      'Preview unavailable': 'Vorschau nicht verfügbar',
      'File not found': 'Datei nicht gefunden',
      'Permission Required': 'Berechtigung erforderlich',
      'Allow': 'Erlauben',
      'Please allow storage access to continue.':
          'Erlauben Sie den Speicherzugriff, um fortzufahren.',
      'Please allow camera access to continue.':
          'Erlauben Sie den Kamerazugriff, um fortzufahren.',
      'Please allow access to continue.':
          'Erlauben Sie den Zugriff, um fortzufahren.',
      'Sort By': 'Sortieren nach',
      'Date(Newest First)': 'Datum (neueste zuerst)',
      'Date(Oldest First)': 'Datum (älteste zuerst)',
      'Name(A-Z)': 'Name (A-Z)',
      'Name(Z-A)': 'Name (Z-A)',
      'Cancel': 'Abbrechen',
      '{n} Selected': '{n} ausgewählt',
      'Select All': 'Alle auswählen',
      'Delete': 'Löschen',
      'Files': 'Dateien',
      'Tools': 'Werkzeuge',
      'Search...': 'Suchen...',
      'All': 'Alle',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'Fügen Sie das Widget hinzu, um sofort auf Funktionen zuzugreifen!',
      'Grant': 'Erlauben',
      'Local Storage': 'Lokaler Speicher',
      'Sort': 'Sortieren',
      'Select': 'Auswählen',
      'No permissions granted': 'Keine Berechtigungen erteilt',
      'Permission is required to access all files':
          'Für den Zugriff auf alle Dateien ist eine Berechtigung erforderlich',
      'Go to settings': 'Zu den Einstellungen',
      'PDF': 'PDF',
      'Your pocket file pro': 'Ihre Dateien immer griffbereit',
      'Unlock Full PDF Potential': 'Das volle PDF-Potenzial ausschöpfen',
      'Step 1: find PDF flow in the list below.':
          'Schritt 1: Suchen Sie PDF flow in der Liste unten.',
      'Step 2: toggle the switch to ON.':
          'Schritt 2: Schalten Sie den Schalter ein.',
      'Continue': 'Weiter',
      'Later': 'Später',
      'Almost there! Unlock your full potential':
          'Fast geschafft! Nutzen Sie das volle Potenzial',
      'Find {n} below and toggle the switch to ON.':
          'Suchen Sie unten nach {n} und schalten Sie den Schalter ein.',
    },
    'es': {
      'PDF tools': 'Herramientas PDF',
      'Scan To': 'Escanear a',
      'Image To': 'Imagen a',
      'System': 'Sistema',
      'Add Widget': 'Añadir widget',
      'Add widget with one click to open files':
          'Añade el widget para abrir archivos con un toque',
      'Home': 'Inicio',
      'Merge': 'Combinar',
      'Import': 'Importar',
      'Convert': 'Convertir',
      'Add': 'Añadir',
      'Why are you uninstalling?': '¿Por qué desinstalas la aplicación?',
      'Hard to use': 'Es difícil de usar',
      'Frequent ad interference':
          'Los anuncios aparecen con demasiada frecuencia',
      'Poor PDF reading experience': 'Mala experiencia de lectura de PDF',
      'Too many notifications': 'Demasiadas notificaciones',
      "Editing features don't meet needs":
          'Las funciones de edición no satisfacen mis necesidades',
      'Phone has built-in PDF tools': 'El teléfono ya incluye herramientas PDF',
      'Other (Please specify)': 'Otro (especifica el motivo)',
      'Please enter the reason for uninstalling All PDF':
          'Introduce el motivo por el que desinstalas All PDF',
      "Don't uninstall for now": 'No desinstalar por ahora',
      'Uninstall': 'Desinstalar',
      'New version coming soon!': '¡Pronto llegará una nueva versión!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Hemos recibido tus comentarios y son muy importantes. Seguimos mejorando la experiencia del producto y pronto lanzaremos una nueva versión. ¡Quédate con nosotros!',
      'Continue using for free': 'Seguir usando gratis',
      'Leave anyway': 'Salir de todos modos',
      'Preference': 'Preferencias',
      'App Language': 'Idioma de la aplicación',
      'Tools & Settings': 'Herramientas y ajustes',
      'This app has an update': 'Esta aplicación tiene una actualización',
      'Please upgrade to enjoy the latest functions.':
          'Actualiza para disfrutar de las funciones más recientes.',
      'All notifications': 'Todas las notificaciones',
      'Update now': 'Actualizar ahora',
      'Welcome': 'Bienvenido',
      'Choose your preferred language to get started.':
          'Elige tu idioma preferido para comenzar.',
      'OK': 'Aceptar',
      'Color': 'Color',
      'Width': 'Grosor',
      'Edit': 'Editar',
      'Save': 'Guardar',
      'Saving...': 'Guardando...',
      'Saved successfully': 'Guardado correctamente',
      'Preview unavailable': 'Vista previa no disponible',
      'File not found': 'Archivo no encontrado',
      'Permission Required': 'Permiso requerido',
      'Allow': 'Permitir',
      'Please allow storage access to continue.':
          'Permite el acceso al almacenamiento para continuar.',
      'Please allow camera access to continue.':
          'Permite el acceso a la cámara para continuar.',
      'Please allow access to continue.': 'Permite el acceso para continuar.',
      'Sort By': 'Ordenar por',
      'Date(Newest First)': 'Fecha (más reciente primero)',
      'Date(Oldest First)': 'Fecha (más antigua primero)',
      'Name(A-Z)': 'Nombre (A-Z)',
      'Name(Z-A)': 'Nombre (Z-A)',
      'Cancel': 'Cancelar',
      '{n} Selected': '{n} seleccionado(s)',
      'Select All': 'Seleccionar todo',
      'Delete': 'Eliminar',
      'Files': 'Archivos',
      'Tools': 'Herramientas',
      'Search...': 'Buscar...',
      'All': 'Todos',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          '¡Añade el widget para acceder al instante a las funciones!',
      'Grant': 'Permitir',
      'Local Storage': 'Almacenamiento local',
      'Sort': 'Ordenar',
      'Select': 'Seleccionar',
      'No permissions granted': 'No se concedieron permisos',
      'Permission is required to access all files':
          'Se necesita permiso para acceder a todos los archivos',
      'Go to settings': 'Ir a ajustes',
      'PDF': 'PDF',
      'Your pocket file pro': 'Tus archivos siempre a mano',
      'Unlock Full PDF Potential': 'Desbloquea todo el potencial de PDF',
      'Step 1: find PDF flow in the list below.':
          'Paso 1: busca PDF flow en la lista de abajo.',
      'Step 2: toggle the switch to ON.': 'Paso 2: activa el interruptor.',
      'Continue': 'Continuar',
      'Later': 'Más tarde',
      'Almost there! Unlock your full potential':
          '¡Ya casi está! Desbloquea todo tu potencial',
      'Find {n} below and toggle the switch to ON.':
          'Busca {n} abajo y activa el interruptor.',
    },
    'it': {
      'PDF tools': 'Strumenti PDF',
      'Scan To': 'Scansiona in',
      'Image To': 'Immagine in',
      'System': 'Sistema',
      'Add Widget': 'Aggiungi widget',
      'Add widget with one click to open files':
          'Aggiungi il widget per aprire i file con un tocco',
      'Home': 'Home',
      'Merge': 'Unisci',
      'Import': 'Importa',
      'Convert': 'Converti',
      'Add': 'Aggiungi',
      'Why are you uninstalling?': 'Perché stai disinstallando l’app?',
      'Hard to use': 'Difficile da usare',
      'Frequent ad interference': 'Pubblicità troppo frequenti',
      'Poor PDF reading experience': 'Esperienza di lettura PDF scadente',
      'Too many notifications': 'Troppe notifiche',
      "Editing features don't meet needs":
          'Le funzioni di modifica non soddisfano le mie esigenze',
      'Phone has built-in PDF tools':
          'Il telefono dispone già di strumenti PDF',
      'Other (Please specify)': 'Altro (specifica)',
      'Please enter the reason for uninstalling All PDF':
          'Inserisci il motivo per cui disinstalli All PDF',
      "Don't uninstall for now": 'Non disinstallare per ora',
      'Uninstall': 'Disinstalla',
      'New version coming soon!': 'Una nuova versione è in arrivo!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Abbiamo ricevuto il tuo feedback ed è molto importante. Miglioriamo continuamente l’esperienza del prodotto e presto lanceremo una nuova versione. Resta con noi!',
      'Continue using for free': 'Continua a usare gratis',
      'Leave anyway': 'Esci comunque',
      'Preference': 'Preferenze',
      'App Language': 'Lingua dell’app',
      'Tools & Settings': 'Strumenti e impostazioni',
      'This app has an update': 'È disponibile un aggiornamento',
      'Please upgrade to enjoy the latest functions.':
          'Aggiorna per utilizzare le funzioni più recenti.',
      'All notifications': 'Tutte le notifiche',
      'Update now': 'Aggiorna ora',
      'Welcome': 'Benvenuto',
      'Choose your preferred language to get started.':
          'Scegli la lingua che preferisci per iniziare.',
      'OK': 'OK',
      'Color': 'Colore',
      'Width': 'Spessore',
      'Edit': 'Modifica',
      'Save': 'Salva',
      'Saving...': 'Salvataggio...',
      'Saved successfully': 'Salvato correttamente',
      'Preview unavailable': 'Anteprima non disponibile',
      'File not found': 'File non trovato',
      'Permission Required': 'Autorizzazione richiesta',
      'Allow': 'Consenti',
      'Please allow storage access to continue.':
          'Consenti l’accesso alla memoria per continuare.',
      'Please allow camera access to continue.':
          'Consenti l’accesso alla fotocamera per continuare.',
      'Please allow access to continue.': 'Consenti l’accesso per continuare.',
      'Sort By': 'Ordina per',
      'Date(Newest First)': 'Data (più recenti prima)',
      'Date(Oldest First)': 'Data (meno recenti prima)',
      'Name(A-Z)': 'Nome (A-Z)',
      'Name(Z-A)': 'Nome (Z-A)',
      'Cancel': 'Annulla',
      '{n} Selected': '{n} selezionati',
      'Select All': 'Seleziona tutto',
      'Delete': 'Elimina',
      'Files': 'File',
      'Tools': 'Strumenti',
      'Search...': 'Cerca...',
      'All': 'Tutti',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'Aggiungi il widget per accedere subito alle funzioni!',
      'Grant': 'Consenti',
      'Local Storage': 'Memoria locale',
      'Sort': 'Ordina',
      'Select': 'Seleziona',
      'No permissions granted': 'Nessuna autorizzazione concessa',
      'Permission is required to access all files':
          'È necessaria l’autorizzazione per accedere a tutti i file',
      'Go to settings': 'Vai alle impostazioni',
      'PDF': 'PDF',
      'Your pocket file pro': 'I tuoi file sempre a portata di mano',
      'Unlock Full PDF Potential': 'Sblocca tutto il potenziale di PDF',
      'Step 1: find PDF flow in the list below.':
          'Passaggio 1: trova PDF flow nell’elenco qui sotto.',
      'Step 2: toggle the switch to ON.': 'Passaggio 2: attiva l’interruttore.',
      'Continue': 'Continua',
      'Later': 'Più tardi',
      'Almost there! Unlock your full potential':
          'Ci siamo quasi! Sblocca tutto il tuo potenziale',
      'Find {n} below and toggle the switch to ON.':
          'Trova {n} qui sotto e attiva l’interruttore.',
    },
    'pt': {
      'PDF tools': 'Ferramentas PDF',
      'Scan To': 'Digitalizar para',
      'Image To': 'Imagem para',
      'System': 'Sistema',
      'Add Widget': 'Adicionar widget',
      'Add widget with one click to open files':
          'Adicione o widget para abrir arquivos com um toque',
      'Home': 'Início',
      'Merge': 'Mesclar',
      'Import': 'Importar',
      'Convert': 'Converter',
      'Add': 'Adicionar',
      'Why are you uninstalling?':
          'Por que você está desinstalando o aplicativo?',
      'Hard to use': 'Difícil de usar',
      'Frequent ad interference': 'Anúncios muito frequentes',
      'Poor PDF reading experience': 'Experiência ruim de leitura de PDF',
      'Too many notifications': 'Muitas notificações',
      "Editing features don't meet needs":
          'Os recursos de edição não atendem às minhas necessidades',
      'Phone has built-in PDF tools': 'O telefone já possui ferramentas de PDF',
      'Other (Please specify)': 'Outro (especifique)',
      'Please enter the reason for uninstalling All PDF':
          'Informe o motivo para desinstalar o All PDF',
      "Don't uninstall for now": 'Não desinstalar agora',
      'Uninstall': 'Desinstalar',
      'New version coming soon!': 'Uma nova versão será lançada em breve!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Recebemos seu feedback e ele é muito importante. Continuamos aprimorando a experiência do produto e uma nova versão será lançada em breve. Fique conosco!',
      'Continue using for free': 'Continuar usando grátis',
      'Leave anyway': 'Sair mesmo assim',
      'Preference': 'Preferências',
      'App Language': 'Idioma do aplicativo',
      'Tools & Settings': 'Ferramentas e configurações',
      'This app has an update': 'Este aplicativo tem uma atualização',
      'Please upgrade to enjoy the latest functions.':
          'Atualize para aproveitar os recursos mais recentes.',
      'All notifications': 'Todas as notificações',
      'Update now': 'Atualizar agora',
      'Welcome': 'Bem-vindo',
      'Choose your preferred language to get started.':
          'Escolha seu idioma preferido para começar.',
      'OK': 'OK',
      'Color': 'Cor',
      'Width': 'Espessura',
      'Edit': 'Editar',
      'Save': 'Salvar',
      'Saving...': 'Salvando...',
      'Saved successfully': 'Salvo com sucesso',
      'Preview unavailable': 'Pré-visualização indisponível',
      'File not found': 'Arquivo não encontrado',
      'Permission Required': 'Permissão necessária',
      'Allow': 'Permitir',
      'Please allow storage access to continue.':
          'Permita o acesso ao armazenamento para continuar.',
      'Please allow camera access to continue.':
          'Permita o acesso à câmera para continuar.',
      'Please allow access to continue.': 'Permita o acesso para continuar.',
      'Sort By': 'Ordenar por',
      'Date(Newest First)': 'Data (mais recentes primeiro)',
      'Date(Oldest First)': 'Data (mais antigos primeiro)',
      'Name(A-Z)': 'Nome (A-Z)',
      'Name(Z-A)': 'Nome (Z-A)',
      'Cancel': 'Cancelar',
      '{n} Selected': '{n} selecionado(s)',
      'Select All': 'Selecionar tudo',
      'Delete': 'Excluir',
      'Files': 'Arquivos',
      'Tools': 'Ferramentas',
      'Search...': 'Pesquisar...',
      'All': 'Todos',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'Adicione o widget para acessar os recursos instantaneamente!',
      'Grant': 'Permitir',
      'Local Storage': 'Armazenamento local',
      'Sort': 'Ordenar',
      'Select': 'Selecionar',
      'No permissions granted': 'Nenhuma permissão concedida',
      'Permission is required to access all files':
          'É necessária permissão para acessar todos os arquivos',
      'Go to settings': 'Ir para configurações',
      'PDF': 'PDF',
      'Your pocket file pro': 'Seus arquivos sempre à mão',
      'Unlock Full PDF Potential': 'Libere todo o potencial do PDF',
      'Step 1: find PDF flow in the list below.':
          'Etapa 1: encontre PDF flow na lista abaixo.',
      'Step 2: toggle the switch to ON.': 'Etapa 2: ative o interruptor.',
      'Continue': 'Continuar',
      'Later': 'Mais tarde',
      'Almost there! Unlock your full potential':
          'Quase lá! Libere todo o seu potencial',
      'Find {n} below and toggle the switch to ON.':
          'Encontre {n} abaixo e ative o interruptor.',
    },
    'ru': {
      'PDF tools': 'Инструменты PDF',
      'Scan To': 'Сканировать в',
      'Image To': 'Изображение в',
      'System': 'Система',
      'Add Widget': 'Добавить виджет',
      'Add widget with one click to open files':
          'Добавьте виджет, чтобы открывать файлы одним нажатием',
      'Home': 'Главная',
      'Merge': 'Объединить',
      'Import': 'Импорт',
      'Convert': 'Конвертировать',
      'Add': 'Добавить',
      'Why are you uninstalling?': 'Почему вы удаляете приложение?',
      'Hard to use': 'Сложно пользоваться',
      'Frequent ad interference': 'Слишком частая реклама',
      'Poor PDF reading experience': 'Неудобно читать PDF',
      'Too many notifications': 'Слишком много уведомлений',
      "Editing features don't meet needs":
          'Функции редактирования не отвечают моим потребностям',
      'Phone has built-in PDF tools':
          'В телефоне уже есть встроенные инструменты PDF',
      'Other (Please specify)': 'Другое (укажите причину)',
      'Please enter the reason for uninstalling All PDF':
          'Укажите причину удаления All PDF',
      "Don't uninstall for now": 'Пока не удалять',
      'Uninstall': 'Удалить',
      'New version coming soon!': 'Скоро выйдет новая версия!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'Мы получили ваш отзыв, и он очень важен для нас. Мы постоянно улучшаем приложение, и скоро выйдет новая версия. Оставайтесь с нами!',
      'Continue using for free': 'Продолжить бесплатно',
      'Leave anyway': 'Всё равно уйти',
      'Preference': 'Настройки',
      'App Language': 'Язык приложения',
      'Tools & Settings': 'Инструменты и настройки',
      'This app has an update': 'Доступно обновление приложения',
      'Please upgrade to enjoy the latest functions.':
          'Обновите приложение, чтобы использовать новейшие функции.',
      'All notifications': 'Все уведомления',
      'Update now': 'Обновить сейчас',
      'Welcome': 'Добро пожаловать',
      'Choose your preferred language to get started.':
          'Выберите предпочитаемый язык, чтобы начать.',
      'OK': 'ОК',
      'Color': 'Цвет',
      'Width': 'Толщина',
      'Edit': 'Редактировать',
      'Save': 'Сохранить',
      'Saving...': 'Сохранение...',
      'Saved successfully': 'Успешно сохранено',
      'Preview unavailable': 'Предпросмотр недоступен',
      'File not found': 'Файл не найден',
      'Permission Required': 'Требуется разрешение',
      'Allow': 'Разрешить',
      'Please allow storage access to continue.':
          'Разрешите доступ к хранилищу, чтобы продолжить.',
      'Please allow camera access to continue.':
          'Разрешите доступ к камере, чтобы продолжить.',
      'Please allow access to continue.': 'Разрешите доступ, чтобы продолжить.',
      'Sort By': 'Сортировать по',
      'Date(Newest First)': 'Дата (сначала новые)',
      'Date(Oldest First)': 'Дата (сначала старые)',
      'Name(A-Z)': 'Имя (А-Я)',
      'Name(Z-A)': 'Имя (Я-А)',
      'Cancel': 'Отмена',
      '{n} Selected': 'Выбрано: {n}',
      'Select All': 'Выбрать все',
      'Delete': 'Удалить',
      'Files': 'Файлы',
      'Tools': 'Инструменты',
      'Search...': 'Поиск...',
      'All': 'Все',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'Добавьте виджет для быстрого доступа к функциям!',
      'Grant': 'Разрешить',
      'Local Storage': 'Локальное хранилище',
      'Sort': 'Сортировать',
      'Select': 'Выбрать',
      'No permissions granted': 'Разрешения не предоставлены',
      'Permission is required to access all files':
          'Для доступа ко всем файлам требуется разрешение',
      'Go to settings': 'Перейти в настройки',
      'PDF': 'PDF',
      'Your pocket file pro': 'Ваши файлы всегда под рукой',
      'Unlock Full PDF Potential': 'Раскройте весь потенциал PDF',
      'Step 1: find PDF flow in the list below.':
          'Шаг 1: найдите PDF flow в списке ниже.',
      'Step 2: toggle the switch to ON.': 'Шаг 2: включите переключатель.',
      'Continue': 'Продолжить',
      'Later': 'Позже',
      'Almost there! Unlock your full potential':
          'Почти готово! Раскройте весь потенциал',
      'Find {n} below and toggle the switch to ON.':
          'Найдите {n} ниже и включите переключатель.',
    },
    'zh_TW': {
      'PDF tools': 'PDF 工具',
      'Scan To': '掃描轉',
      'Image To': '圖片轉',
      'System': '系統',
      'Add Widget': '加入小工具',
      'Add widget with one click to open files': '加入小工具，一鍵開啟檔案',
      'Home': '首頁',
      'Merge': '合併',
      'Import': '匯入',
      'Convert': '轉換',
      'Add': '加入',
      'Why are you uninstalling?': '為什麼要解除安裝？',
      'Hard to use': '操作不易',
      'Frequent ad interference': '廣告干擾太頻繁',
      'Poor PDF reading experience': 'PDF 閱讀體驗不佳',
      'Too many notifications': '通知太多',
      "Editing features don't meet needs": '編輯功能不符合需求',
      'Phone has built-in PDF tools': '手機已有內建 PDF 工具',
      'Other (Please specify)': '其他（請說明）',
      'Please enter the reason for uninstalling All PDF': '請輸入解除安裝 All PDF 的原因',
      "Don't uninstall for now": '暫時不要解除安裝',
      'Uninstall': '解除安裝',
      'New version coming soon!': '新版本即將推出！',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          '我們已收到您的意見，這些資訊對我們非常重要。我們正持續改善產品體驗，新版本也即將推出，請繼續支持我們！',
      'Continue using for free': '繼續免費使用',
      'Leave anyway': '仍要離開',
      'Preference': '偏好設定',
      'App Language': '應用程式語言',
      'Tools & Settings': '工具與設定',
      'This app has an update': '此應用程式有可用更新',
      'Please upgrade to enjoy the latest functions.': '請更新以使用最新功能。',
      'All notifications': '所有通知',
      'Update now': '立即更新',
      'Welcome': '歡迎',
      'Choose your preferred language to get started.': '選擇偏好的語言以開始使用。',
      'OK': '確定',
      'Color': '顏色',
      'Width': '粗細',
      'Edit': '編輯',
      'Save': '儲存',
      'Saving...': '儲存中...',
      'Saved successfully': '儲存成功',
      'Preview unavailable': '無法預覽',
      'File not found': '找不到檔案',
      'Permission Required': '需要權限',
      'Allow': '允許',
      'Please allow storage access to continue.': '請允許儲存空間存取權限以繼續。',
      'Please allow camera access to continue.': '請允許相機存取權限以繼續。',
      'Please allow access to continue.': '請允許存取權限以繼續。',
      'Sort By': '排序方式',
      'Date(Newest First)': '日期（最新優先）',
      'Date(Oldest First)': '日期（最舊優先）',
      'Name(A-Z)': '名稱（A-Z）',
      'Name(Z-A)': '名稱（Z-A）',
      'Files': '檔案',
      'Search...': '搜尋...',
      'All': '全部',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!': '加入小工具，即刻使用各項功能！',
      'Grant': '授權',
      'Local Storage': '本機儲存空間',
      'Sort': '排序',
      'Select': '選取',
      'No permissions granted': '尚未授予權限',
      'Permission is required to access all files': '存取所有檔案需要權限',
      'Go to settings': '前往設定',
      'Cancel': '取消',
      '{n} Selected': '已選取 {n} 項',
      'Select All': '全選',
      'Delete': '刪除',
      'Tools': '工具',
      'PDF': 'PDF',
      'Your pocket file pro': '隨身檔案專家',
      'Unlock Full PDF Potential': '解鎖 PDF 的完整潛力',
      'Step 1: find PDF flow in the list below.': '步驟 1：在下方清單中找到 PDF flow。',
      'Step 2: toggle the switch to ON.': '步驟 2：將開關切換為開啟。',
      'Continue': '繼續',
      'Later': '稍後',
      'Almost there! Unlock your full potential': '快完成了！解鎖完整功能',
      'Find {n} below and toggle the switch to ON.': '在下方找到 {n}，並將開關切換為開啟。',
    },
    'zh_CN': {
      'PDF tools': 'PDF 工具',
      'Scan To': '扫描转',
      'Image To': '图片转',
      'System': '系统',
      'Add Widget': '添加小组件',
      'Add widget with one click to open files': '添加小组件，一键打开文件',
      'Home': '首页',
      'Merge': '合并',
      'Import': '导入',
      'Convert': '转换',
      'Add': '添加',
      'Why are you uninstalling?': '为什么要卸载？',
      'Hard to use': '使用困难',
      'Frequent ad interference': '广告干扰频繁',
      'Poor PDF reading experience': 'PDF 阅读体验不佳',
      'Too many notifications': '通知太多',
      "Editing features don't meet needs": '编辑功能不能满足需求',
      'Phone has built-in PDF tools': '手机已内置 PDF 工具',
      'Other (Please specify)': '其他（请说明）',
      'Please enter the reason for uninstalling All PDF': '请输入卸载 All PDF 的原因',
      "Don't uninstall for now": '暂时不要卸载',
      'Uninstall': '卸载',
      'New version coming soon!': '新版本即将上线！',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          '我们已收到您的反馈，这些信息对我们非常重要。我们正在持续优化产品体验，新版本也即将上线，请继续支持我们！',
      'Continue using for free': '继续免费使用',
      'Leave anyway': '仍要离开',
      'Preference': '偏好设置',
      'App Language': '应用语言',
      'Tools & Settings': '工具与设置',
      'This app has an update': '此应用有可用更新',
      'Please upgrade to enjoy the latest functions.': '请更新以使用最新功能。',
      'All notifications': '所有通知',
      'Update now': '立即更新',
      'Welcome': '欢迎',
      'Choose your preferred language to get started.': '选择你偏好的语言以开始使用。',
      'OK': '确定',
      'Color': '颜色',
      'Width': '粗细',
      'Edit': '编辑',
      'Save': '保存',
      'Saving...': '保存中...',
      'Saved successfully': '保存成功',
      'Preview unavailable': '无法预览',
      'File not found': '找不到文件',
      'Permission Required': '需要权限',
      'Allow': '允许',
      'Please allow storage access to continue.': '请允许存储访问权限以继续。',
      'Please allow camera access to continue.': '请允许相机访问权限以继续。',
      'Please allow access to continue.': '请允许访问权限以继续。',
      'Sort By': '排序方式',
      'Date(Newest First)': '日期（最新优先）',
      'Date(Oldest First)': '日期（最早优先）',
      'Name(A-Z)': '名称（A-Z）',
      'Name(Z-A)': '名称（Z-A）',
      'Files': '文件',
      'Search...': '搜索...',
      'All': '全部',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!': '添加小组件，即刻使用各项功能！',
      'Grant': '授权',
      'Local Storage': '本地存储',
      'Sort': '排序',
      'Select': '选择',
      'No permissions granted': '尚未授予权限',
      'Permission is required to access all files': '访问所有文件需要相关权限',
      'Go to settings': '前往设置',
      'Cancel': '取消',
      '{n} Selected': '已选择 {n} 项',
      'Select All': '全选',
      'Delete': '删除',
      'Tools': '工具',
      'PDF': 'PDF',
      'Your pocket file pro': '随身文件专家',
      'Unlock Full PDF Potential': '解锁 PDF 的全部潜力',
      'Step 1: find PDF flow in the list below.': '步骤 1：在下方列表中找到 PDF flow。',
      'Step 2: toggle the switch to ON.': '步骤 2：将开关切换为开启。',
      'Continue': '继续',
      'Later': '稍后',
      'Almost there! Unlock your full potential': '即将完成！解锁全部功能',
      'Find {n} below and toggle the switch to ON.': '在下方找到 {n}，并将开关切换为开启。',
    },
    'ar': {
      'PDF tools': 'أدوات PDF',
      'Scan To': 'مسح إلى',
      'Image To': 'صورة إلى',
      'System': 'النظام',
      'Add Widget': 'إضافة أداة',
      'Add widget with one click to open files':
          'أضف الأداة لفتح الملفات بنقرة واحدة',
      'Home': 'الرئيسية',
      'Merge': 'دمج',
      'Import': 'استيراد',
      'Convert': 'تحويل',
      'Add': 'إضافة',
      'Why are you uninstalling?': 'لماذا تقوم بإلغاء تثبيت التطبيق؟',
      'Hard to use': 'صعب الاستخدام',
      'Frequent ad interference': 'الإعلانات مزعجة ومتكررة',
      'Poor PDF reading experience': 'تجربة قراءة PDF غير جيدة',
      'Too many notifications': 'إشعارات كثيرة جدًا',
      "Editing features don't meet needs": 'ميزات التحرير لا تلبي احتياجاتي',
      'Phone has built-in PDF tools': 'الهاتف يحتوي بالفعل على أدوات PDF',
      'Other (Please specify)': 'أخرى (يرجى التوضيح)',
      'Please enter the reason for uninstalling All PDF':
          'يرجى إدخال سبب إلغاء تثبيت All PDF',
      "Don't uninstall for now": 'عدم إلغاء التثبيت الآن',
      'Uninstall': 'إلغاء التثبيت',
      'New version coming soon!': 'إصدار جديد قريبًا!',
      'Your feedback has been received! This information is vital to us. We are continuously optimizing the product experience, and a new version will be launched soon. Please stay with us!':
          'لقد تلقينا ملاحظاتك وهي مهمة جدًا لنا. نواصل تحسين تجربة المنتج وسيتم إطلاق إصدار جديد قريبًا. ابق معنا!',
      'Continue using for free': 'متابعة الاستخدام مجانًا',
      'Leave anyway': 'المغادرة على أي حال',
      'Preference': 'التفضيلات',
      'App Language': 'لغة التطبيق',
      'Tools & Settings': 'الأدوات والإعدادات',
      'This app has an update': 'يتوفر تحديث لهذا التطبيق',
      'Please upgrade to enjoy the latest functions.':
          'حدّث التطبيق للاستمتاع بأحدث الميزات.',
      'All notifications': 'جميع الإشعارات',
      'Update now': 'التحديث الآن',
      'Welcome': 'مرحبًا',
      'Choose your preferred language to get started.':
          'اختر لغتك المفضلة للبدء.',
      'OK': 'موافق',
      'Color': 'اللون',
      'Width': 'السُمك',
      'Edit': 'تعديل',
      'Save': 'حفظ',
      'Saving...': 'جارٍ الحفظ...',
      'Saved successfully': 'تم الحفظ بنجاح',
      'Preview unavailable': 'المعاينة غير متاحة',
      'File not found': 'الملف غير موجود',
      'Permission Required': 'الإذن مطلوب',
      'Allow': 'السماح',
      'Please allow storage access to continue.':
          'يرجى السماح بالوصول إلى مساحة التخزين للمتابعة.',
      'Please allow camera access to continue.':
          'يرجى السماح بالوصول إلى الكاميرا للمتابعة.',
      'Please allow access to continue.': 'يرجى السماح بالوصول للمتابعة.',
      'Sort By': 'الترتيب حسب',
      'Date(Newest First)': 'التاريخ (الأحدث أولاً)',
      'Date(Oldest First)': 'التاريخ (الأقدم أولاً)',
      'Name(A-Z)': 'الاسم (أ-ي)',
      'Name(Z-A)': 'الاسم (ي-أ)',
      'Cancel': 'إلغاء',
      '{n} Selected': 'تم تحديد {n}',
      'Select All': 'تحديد الكل',
      'Delete': 'حذف',
      'Files': 'الملفات',
      'Tools': 'الأدوات',
      'Search...': 'بحث...',
      'All': 'الكل',
      'Word': 'Word',
      'Excel': 'Excel',
      'To access features instantly, add the widget!':
          'أضف الأداة للوصول الفوري إلى الميزات!',
      'Grant': 'السماح',
      'Local Storage': 'التخزين المحلي',
      'Sort': 'ترتيب',
      'Select': 'تحديد',
      'No permissions granted': 'لم يتم منح الأذونات',
      'Permission is required to access all files':
          'يلزم الإذن للوصول إلى جميع الملفات',
      'Go to settings': 'الانتقال إلى الإعدادات',
      'PDF': 'PDF',
      'Your pocket file pro': 'خبير ملفاتك في جيبك',
      'Unlock Full PDF Potential': 'أطلق العنان لإمكانات PDF الكاملة',
      'Step 1: find PDF flow in the list below.':
          'الخطوة 1: ابحث عن PDF flow في القائمة أدناه.',
      'Step 2: toggle the switch to ON.': 'الخطوة 2: فعّل مفتاح التبديل.',
      'Continue': 'متابعة',
      'Later': 'لاحقًا',
      'Almost there! Unlock your full potential':
          'أوشكت على الانتهاء! أطلق العنان لإمكاناتك الكاملة',
      'Find {n} below and toggle the switch to ON.':
          'ابحث عن {n} أدناه وفعّل مفتاح التبديل.',
    },
  };
}
